### ISSUE TITLE
ios:App crashes when opening a file

### ISSUE THREAD

**Issue by wenjianli92** [pwlin/cordova-plugin-file-opener2#242]
I am using the latest 2.1.2 version
I use ionic,  ionic info:

App crashes when opening a file using the open method， at iphone 6 plus and ipad
ios:12.1

![Uploading image.png…]()

**Comment by wenjianli92** [comment]
![image](https://user-images.githubusercontent.com/29296692/50330886-d49e6000-0537-11e9-9a73-2ed5d7544b3a.png)

**Comment by wenjianli92** [comment]
![image](https://user-images.githubusercontent.com/29296692/50330962-0b747600-0538-11e9-820c-765c9eaee80a.png)
Display the above error in xcode

**Comment by shnist** [comment]
hi @wenjianli92, thanks for raising this issue. There was some worked that was merged in recently that seems to be causing a lot of problems now. I forgot it was there when I published the patched version. I'm going to remove it from the master branch for now and release a new patch version today.

**Comment by wenjianli92** [comment]
@shnist  Still can't, reported the following error
![image](https://user-images.githubusercontent.com/29296692/50339061-58b11180-0551-11e9-95ff-bdcb7efdbe39.png)

**Comment by wenjianli92** [comment]
hi @shnist, Sorry, I stopped this job for some reason ,I use ionic ,Ionic information is as follows:
![image](https://user-images.githubusercontent.com/29296692/50409647-280df800-082f-11e9-9e12-76829583b040.png)


I am using a third-party plugin to do the function of sending and receiving files in a chat session, and using one of its APIs to perform the download. After the download is successful, it will return a path（“this.fileurl” in the code below）.

console.log(this.fileurl,mymimetype,'=====================fileurl,mymimetype,63');
await this.fileOpener.open(this.fileurl,mymimetype);

The xcode output is as follows:

![image](https://user-images.githubusercontent.com/29296692/50410264-bdf75200-0832-11e9-9bf7-4143aed57dee.png)

The file path starts with '/var/mobile'. Is this wrong? Then how can I get the correct file path?

**Comment by wenjianli92** [comment]
This problem is caused by the wrong path：

let localentry: Entry = await this.file.resolveLocalFilesystemUrl('file://'+this.fileurl);
let fileEntry = localentry as FileEntry;
fileEntry.file((myfile)=>{
    if(this.nativeService.isIos()){
        this.fileOpener.open(localentry.nativeURL,myfile.type);
    }
},(err)=>{
    console.error(err);
});

**Comment by shnist** [comment]
hi @wenjianli92, glad to hear you were able to resolve your issue.
